local ADDON_NAME, ns = ...
local NephUI = ns.Addon

NephUI.viewers = {
    "EssentialCooldownViewer",
    "UtilityCooldownViewer",
    "BuffIconCooldownViewer",
}

local defaults = {
    profile = {
        general = {
            globalTexture = "Neph",
            globalFont = "Expressway",
            applyGlobalFontToBlizzard = false,
            eyefinity = false,
            ultrawide = false,
            uiScale = nil,
        },
        viewers = {
            general = {
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
                procGlow = {
                    enabled = true,
                    glowType = "Pixel Glow",
                    loopColor = {0.95, 0.95, 0.32, 1},
                    lcgLines = 14,
                    lcgFrequency = 0.25,
                    lcgThickness = 1,
                    lcgXOffset = -11.00,
                    lcgYOffset = -11.00,
                },
            },
            EssentialCooldownViewer = {
                enabled          = true,
                iconSize         = 58,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                padding          = 5,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 16,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
            UtilityCooldownViewer = {
                enabled          = true,
                iconSize         = 54,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                padding          = 5,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 16,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
            BuffIconCooldownViewer = {
                enabled          = true,
                iconSize         = 48,
                aspectRatioCrop  = 1.0,
                spacing          = 1,
                zoom             = 0.08,
                padding          = 5,
                borderSize       = 1,
                borderColor      = { 0, 0, 0, 1 },
                chargeTextAnchor = "BOTTOMRIGHT",
                countTextSize    = 14,
                countTextOffsetX = 0,
                countTextOffsetY = 0,
                rowLimit         = 0,
                primaryDirection = "CENTERED_HORIZONTAL",
                secondaryDirection = nil,
                cooldownFontSize = 18,
                cooldownTextColor = {1, 1, 1, 1},
                cooldownShadowOffsetX = 0,
                cooldownShadowOffsetY = 0,
            },
        },
        powerBar = {
            enabled           = true,
            attachTo          = "EssentialCooldownViewer",
            anchorPoint       = "TOP",
            height            = 14,
            offsetY           = 4,
            width             = 0,
            texture           = nil,  
            useClassColor     = true,
            showManaAsPercent = true,
            showText          = true,
            showTicks         = true, 
            textSize          = 20,
            textX             = 1,
            textY             = 2,
            bgColor           = { 0.15, 0.15, 0.15, 1 },
        },
        secondaryPowerBar = {
            enabled       = true,
            attachTo      = "EssentialCooldownViewer",
            anchorPoint   = "TOP",
            height        = 14,
            offsetY       = 20,
            width         = 0,
            texture       = nil,  
            useClassColor = false,
            showText      = true,
            showTicks     = true,
            hideBarShowText = false,
            showFragmentedPowerBarText  = false,
            textSize      = 16,
            textX         = 0.5,
            textY         = 2,
            runeTimerTextSize = 10,
            runeTimerTextX    = 0,
            runeTimerTextY    = 0,
            bgColor       = { 0.15, 0.15, 0.15, 1 },
        },
        castBar = {
            enabled       = true,
            attachTo      = "EssentialCooldownViewer",
            height        = 24,
            offsetY       = -83,
            texture       = nil,  
            color         = { 1.0, 0.7, 0.0, 1.0 },
            useClassColor = false,
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        targetCastBar = {
            enabled       = true,
            attachTo      = "NephUI_Target",
            height        = 24,
            offsetY       = -38,
            texture       = nil,  
            color         = { 1.0, 0.0, 0.0, 1.0 },
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        focusCastBar = {
            enabled       = true,
            attachTo      = "NephUI_Focus",
            height        = 24,
            offsetY       = 30,
            texture       = nil,  
            color         = { 1.0, 0.0, 0.0, 1.0 },
            textSize      = 16,
            width         = 0,
            bgColor       = { 0.1, 0.1, 0.1, 1 },
            showTimeText  = true,
        },
        customIcons = {
            enabled = true,
            countTextSize = 16,
            countTextX = -2,
            countTextY = 2,
            trackedItems = {},
            items = {
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "Right",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = -91,
                offsetY = -47,
                hideUnusableItems = false,
            },
            trinkets = {
                trinket1 = true,
                trinket2 = true,
                weapon1 = true,
                weapon2 = true,
                iconSize = 44,
                aspectRatioCrop = 1.0,
                spacing = 1,
                rowLimit = 0,
                growthDirection = "Left",
                borderSize = 1,
                borderColor = { 0, 0, 0, 1 },
                anchorFrame = "NephUI_Player",
                offsetX = 90,
                offsetY = 47,
                hideUnusableItems = false,
            },
        },
        unitFrames = {
            enabled = true,
            General = {
                ShowEditModeAnchors = false,
                Font = "Expressway",
                FontFlag = "OUTLINE",
                FontShadows = {
                    Color = {0, 0, 0, 0},
                    OffsetX = 0,
                    OffsetY = 0
                },
                ForegroundTexture = nil,  
                BackgroundTexture = nil,  
                CustomColors = {
                    Reaction = {
                        [1] = {204/255, 64/255, 64/255},
                        [2] = {204/255, 64/255, 64/255},
                        [3] = {204/255, 128/255, 64/255},
                        [4] = {255/255, 234/255, 126/255},
                        [5] = {64/255, 204/255, 64/255},
                        [6] = {64/255, 204/255, 64/255},
                        [7] = {64/255, 204/255, 64/255},
                        [8] = {64/255, 204/255, 64/255},
                    },
                    Power = {
                        [0] = {0, 0.50, 1},
                        [1] = {1, 0, 0},
                        [2] = {1, 0.5, 0.25},
                        [3] = {1, 1, 0},
                        [6] = {0, 0.82, 1},
                        [8] = {0.3, 0.52, 0.9},
                        [11] = {0, 0.5, 1},
                        [13] = {0.4, 0, 0.8},
                        [17] = {0.79, 0.26, 0.99},
                        [18] = {1, 0.61, 0}
                    },
                },
            },
            player = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 48,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "EssentialCooldownViewer",
                    AnchorToCooldown = true,
                    OffsetX = 0,
                    OffsetY = 0,
                    ClassColor = true,
                    ReactionColor = false,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                AbsorbBar = {
                    Texture = "Neph",
                    FillDirection = "left",
                    AnchorMode = "health",
                    Color = {0.3, 0.5, 0.8, 0.8},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
            },
            target = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 48,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "EssentialCooldownViewer",
                    AnchorToCooldown = true,
                    OffsetX = 0,
                    OffsetY = 0,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = false,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                AbsorbBar = {
                    Texture = "Neph",
                    FillDirection = "left",
                    AnchorMode = "health",
                    Color = {0.3, 0.5, 0.8, 0.8},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = true,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
                Auras = {
                    Width = 0,
                    Height = 63,
                    Alpha = 1,
                    RowLimit = 0,
                    OffsetX = 0,
                    OffsetY = 1,
                    Spacing = 1,
                    ShowBuffs = true,
                    ShowDebuffs = true,
                    cooldownFontSize = 18,
                    cooldownTextColor = {1, 1, 1, 1},
                    cooldownShadowOffsetX = 0,
                    cooldownShadowOffsetY = 0,
                },
            },
            targettarget = {
                Enabled = true,
                Frame = {
                    Width = 122,
                    Height = 21,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Target",
                    OffsetX = 196,
                    OffsetY = -14,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 0,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    },
                    Health = {
                        Enabled = false,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 14,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                },
            },
            pet = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 21,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Player",
                    OffsetX = 0,
                    OffsetY = -36,
                    ClassColor = true,
                    ReactionColor = false,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "CENTER",
                        AnchorTo = "CENTER",
                        OffsetX = 0,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    },
                    Health = {
                        Enabled = false,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
            },
            focus = {
                Enabled = true,
                Frame = {
                    Width = 269,
                    Height = 32,
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    AnchorFrame = "NephUI_Player",
                    OffsetX = 0,
                    OffsetY = 86,
                    ClassColor = true,
                    ReactionColor = true,
                    FGColor = {26/255, 26/255, 26/255, 1.0},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                PowerBar = {
                    Enabled = true,
                    Height = 2,
                    ColorByType = true,
                    ColorBackgroundByType = true,
                    FGColor = {8/255, 8/255, 8/255, 0.8},
                    BGColor = {45/255, 45/255, 45/255, 1.0},
                },
                Tags = {
                    Name = {
                        Enabled = true,
                        AnchorFrom = "LEFT",
                        AnchorTo = "LEFT",
                        OffsetX = 3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        ColorByStatus = false,
                    },
                    Health = {
                        Enabled = true,
                        AnchorFrom = "RIGHT",
                        AnchorTo = "RIGHT",
                        OffsetX = -3,
                        OffsetY = 0,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayPercent = true,
                    },
                    Power = {
                        Enabled = false,
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        OffsetX = -3,
                        OffsetY = 3,
                        FontSize = 12,
                        Color = {1, 1, 1, 1},
                        DisplayStyle = "both",
                    },
                },
            },
        },
        chat = {
            enabled = true,
            backgroundColor = { 0, 0, 0, 1 },
            hideQuickJoinToastButton = false,
            quickJoinToastButtonOffsetX = 31,
            quickJoinToastButtonOffsetY = -23,
        },
        minimap = {
            enabled = true,
            size = 230,
            borderSize = 2,
            lock = false,
            position = {"CENTER", "CENTER", 0, 0},
            scale = 1,
            autoZoom = true,
            mouseWheelZoom = true,
            hideBlizzardButtons = true,
            hideZoomButtons = true,
            hideTrackingButton = true,
            hideDifficultyIcon = false,
            difficultyIcon = {
                anchor = "Top Right",
                offsetX = -5,
                offsetY = -5,
            },
            hideMailButton = false,
            mailIcon = {
                anchor = "Top Left",
                offsetX = 3,
                offsetY = -3,
            },
            hideCalendarButton = true,
            hideMissionsButton = true,
            hideAddonCompartment = true,
            zoneText = {
                enabled = true,
                fontSize = 14,
                anchor = "Top",
                offsetX = 0,
                offsetY = -5,
                useCustomColor = false,
                color = {1, 0.82, 0, 1},
                colorNormal = {1, 0.82, 0, 1},
                colorSanctuary = {0.41, 0.8, 0.94, 1},
                colorArena = {1.0, 0.1, 0.1, 1},
                colorFriendly = {0.1, 1.0, 0.1, 1},
                colorHostile = {1.0, 0.1, 0.1, 1},
                colorContested = {1.0, 0.7, 0.0, 1},
            },
            clock = {
                enabled = true,
                fontSize = 16,
                anchor = "Bottom Left",
                color = {1, 1, 1, 1},
                offsetX = 4,
                offsetY = 4,
            },
            fps = {
                enabled = true,
                fontSize = 16,
                anchor = "Bottom Right",
                color = {1, 1, 1, 1},
                updateFrequency = 2,
                offsetX = -4,
                offsetY = 4,
            },
        },
        actionBars = {
            enabled = true,
            backdropColor = {0.1, 0.1, 0.1, 1},
            borderColor = {0.3, 0.3, 0.3, 1},
            font = nil, -- nil = use global font
            mouseover = {
                enabled = false,
                alpha = 0.0,
                bars = {
                    bar1 = false,
                    bar2 = false,
                    bar3 = false,
                    bar4 = false,
                    bar5 = false,
                    bar6 = false,
                    bar7 = false,
                    bar8 = false,
                    petBar = false,
                    stanceBar = false,
                },
            },
            keybindText = {
                hide = false,
                fontColor = {0.75, 0.75, 0.75, 1},
                fontSize = 14,
                offsetX = -2,
                offsetY = -4,
            },
            macroText = {
                hide = false,
                fontColor = {1, 1, 1, 1},
                fontSize = 10,
                offsetX = 0,
                offsetY = 2,
            },
            countText = {
                hide = false,
                fontColor = {1, 1, 1, 1},
                fontSize = 16,
                offsetX = -2,
                offsetY = 4,
            },
            procGlow = {
                enabled = true,
                glowType = "Pixel Glow",
                loopColor = {0.95, 0.95, 0.32, 1},
                lcgLines = 14,
                lcgFrequency = 0.25,
                lcgThickness = 2,
                lcgXOffset = -7,
                lcgYOffset = -7,
            },
        },
        buffDebuffFrames = {
            enabled = true,
            layout = {
                iconsPerRow = 12,
                iconSpacing = 5,
                rowSpacing = 5,
                anchorSide = "TOPRIGHT",
                growthHorizontal = "LEFT",
                growthVertical = "DOWN",
            },
            buffs = {
                iconSize = 38,
                layout = {
                    iconsPerRow = 12,
                    iconSpacing = 11,
                    rowSpacing = 1,
                    anchorSide = "TOPRIGHT",
                },
                duration = {
                    enabled = true,
                    anchorPoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
                count = {
                    enabled = true,
                    anchorPoint = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
            },
            debuffs = {
                iconSize = 38,
                layout = {
                    iconsPerRow = 12,
                    iconSpacing = 11,
                    rowSpacing = 1,
                    anchorSide = "TOPRIGHT",
                },
                duration = {
                    enabled = true,
                    anchorPoint = "CENTER",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
                count = {
                    enabled = true,
                    anchorPoint = "BOTTOMRIGHT",
                    offsetX = 0,
                    offsetY = 0,
                    fontSize = 12,
                    fontFlag = "OUTLINE",
                    textColor = {1, 1, 1, 1},
                },
            },
        },
    },
}

NephUI.defaults = defaults

